/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagePerson;

import Business.Business;
import Business.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ftl
 */
public class UpdatePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private Person person;
    /**
     * Creates new form UpdatePersonJPanel
     */
    public UpdatePersonJPanel(JPanel userProcessContainer, Business business, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.person = person;
        
        firstNameTxt.setText(person.getFirstName());
        lastNameTxt.setText(person.getLastName());
        ssnTxt.setText(person.getSsn());
        dobMonthCBox.setSelectedItem(person.getDobMonth());
        dobDayTxt.setText(person.getDobDay()+"");
        dobYearTxt.setText(person.getDobYear()+"");
        addressTxt.setText(person.getAddress());
    }

    public String validateSSN(String input) {
        String[] fullSSN = input.split("-");
                
        if (fullSSN.length != 3 || fullSSN[0].length() != 3 || fullSSN[1].length() != 2 || fullSSN[2].length() != 4)
            return null;
        
        try {
            Integer.parseInt(fullSSN[0]);
            Integer.parseInt(fullSSN[1]);
            Integer.parseInt(fullSSN[2]);
        }
        catch (NumberFormatException e) {
            return null;
        }   

        return input;
    }
    
    public boolean isAlpha(String name) {
        char[] chars = name.toCharArray();

        for (char c : chars) {
            if(!Character.isLetter(c)) {
                return false;
            }
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ssnTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        dobDayTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dobMonthCBox = new javax.swing.JComboBox<>();
        firstNameTxt = new javax.swing.JTextField();
        dobYearTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        jLabel5.setText("First");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Last");

        jLabel1.setText("Name:");

        jLabel2.setText("SSN: ");

        jLabel3.setText("Date of Birth:");

        jLabel4.setText("Address:");

        dobMonthCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May",
            "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" }));

jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
jLabel7.setText("View / Update Person Info");

backBtn.setText("< Back");
backBtn.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        backBtnActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backBtn)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(updateBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dobMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel7)))
            .addContainerGap(76, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dobDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(dobMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dobYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(updateBtn)
                .addComponent(backBtn))
            .addContainerGap(42, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
// validation of name
        if (isAlpha(firstNameTxt.getText())) 
            person.setFirstName(firstNameTxt.getText());
        else {
            JOptionPane.showMessageDialog(null, "Please input a valid First Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (isAlpha(lastNameTxt.getText())) 
            person.setFirstName(lastNameTxt.getText());
        else {
            JOptionPane.showMessageDialog(null, "Please input a valid Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // validation of SSN
        if(validateSSN(ssnTxt.getText()) == null) {
            JOptionPane.showMessageDialog(null, "Please input a valid SSN", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
            person.setSsn(ssnTxt.getText());
        
        person.setDobMonth(dobMonthCBox.getSelectedItem().toString());
        
        // validation of date number
        try {
            Integer.parseInt(dobDayTxt.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input number in Day field", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }         
        int dobDay = Integer.parseInt(dobDayTxt.getText());
        if (dobDay <1 || dobDay >31 ) {
            JOptionPane.showMessageDialog(null, "Please input a valid Day.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }                
        person.setDobDay(dobDay);
        
        try {
            Integer.parseInt(dobYearTxt.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input number in Year field", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }         
        int dobYear = Integer.parseInt(dobYearTxt.getText());
        if (dobYear <1900 || dobYear >2100 ) {
            JOptionPane.showMessageDialog(null, "Please input a valid Year.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }                
        person.setDobDay(dobYear);        
        person.setAddress(addressTxt.getText());
        JOptionPane.showMessageDialog(null, "Person Successfully updated.");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        // Avoid error when back to search panel
        try {
            ManagePersonJPanel managePersonJPanel = (ManagePersonJPanel) component;
            managePersonJPanel.populateTable();
        }
        catch(Exception e) {
            return;
        }
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dobDayTxt;
    private javax.swing.JComboBox<String> dobMonthCBox;
    private javax.swing.JTextField dobYearTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField ssnTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
