/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;
import Business.Airplanes;
import Business.Fleet;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Tianli Feng
 */
public class CreateJPanel extends javax.swing.JPanel {

    /** Record the user input and creates airplanes */
    private Fleet flt;
    public CreateJPanel(Fleet flt) {
        initComponents();
        this.flt = flt;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menufactureTxt = new javax.swing.JTextField();
        airportTxt = new javax.swing.JTextField();
        availMonthCBox = new javax.swing.JComboBox<>();
        expireMonthCBox = new javax.swing.JComboBox<>();
        serialNumTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        seatCapacityTxt = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        menufYearTxt = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        availYearTxt = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        expireYearTxt = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        modelNumTxt = new javax.swing.JTextField();

        jLabel1.setText("Serial Number:");

        jLabel2.setText("Model Number:");

        jLabel3.setText("Menufacture:");

        jLabel4.setText("Seat Capacity:");

        jLabel5.setText("Menufacturing Year:");

        jLabel6.setText("Availability Date:");

        jLabel7.setText("Maintenance Expiration:");

        jLabel8.setText("Airport:");

        availMonthCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr",
            "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"}));

expireMonthCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Jan", "Feb", "Mar", "Apr",
    "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"}));

    saveBtn.setText("Save");
    saveBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(availMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(availYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(expireMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expireYearTxt))
                        .addComponent(serialNumTxt)
                        .addComponent(menufactureTxt)
                        .addComponent(seatCapacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menufYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(airportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(saveBtn)))
            .addGap(0, 55, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(menufactureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(seatCapacityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(menufYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(availMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(availYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(expireMonthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(expireYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(airportTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addGap(29, 29, 29)
            .addComponent(saveBtn)
            .addContainerGap(43, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void recordUpdateTime() {
        //Create an instance of SimpleDateFormat used for formatting
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        // Get the date today using Calendar object.
        Date today = Calendar.getInstance().getTime();
        // Using DateFormat format method we can create a string 
        // representation of a date with the defined format.
        String todayDate = df.format(today);
        flt.setFleetUpdateDate(todayDate);
    }
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        boolean formattedFieldEmpty = false;
        
        String menufacture = menufactureTxt.getText();
        String modelNum = modelNumTxt.getText();
        String serialNum = serialNumTxt.getText();
        int seatCapacity = -1;
        int menufYear = -1;
        String availMonth = (String) availMonthCBox.getSelectedItem();
        int availYear = -1;
        String expireMonth = (String) expireMonthCBox.getSelectedItem();
        int expireYear = -1;
        try {
            seatCapacity = Integer.parseInt(seatCapacityTxt.getText().replaceAll(",", "")); 
            menufYear = Integer.parseInt(menufYearTxt.getText().replaceAll(",", ""));
            availYear = Integer.parseInt(availYearTxt.getText().replaceAll(",", "")); 
            expireYear = Integer.parseInt(expireYearTxt.getText().replaceAll(",", "")); 
        }
        catch(NumberFormatException e) {formattedFieldEmpty = true;}
        String airport = airportTxt.getText();
        
        // Validate empty text field
        if (menufacture.isEmpty() || modelNum.isEmpty() || 
                serialNum.isEmpty() || airport.isEmpty() || formattedFieldEmpty)  {
            JOptionPane.showMessageDialog(null, "No blank field is allowed.");
            return;
        }

        Airplanes ap = flt.addAirplanes();
        ap.setMenufacture(menufacture);
        ap.setModelNum(modelNum);
        ap.setSerialNum(serialNum);
        ap.setSeatCapacity(seatCapacity);  
        ap.setMenufYear(menufYear);
        ap.setAvailMonth(availMonth);
        ap.setAvailYear(availYear);
        ap.setExpireMonth(expireMonth);
        ap.setExpireYear(expireYear);
        ap.setAirport(airport);
        JOptionPane.showMessageDialog(null, "Airplane Added Successfully");
        recordUpdateTime();
        
        menufactureTxt.setText("");
        modelNumTxt.setText("");
        serialNumTxt.setText("");
        seatCapacityTxt.setText("");
        menufYearTxt.setText("");
        availMonthCBox.setSelectedIndex(0);
        menufYearTxt.setText("");
        expireMonthCBox.setSelectedIndex(0);
        expireYearTxt.setText("");
        airportTxt.setText("");

    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airportTxt;
    private javax.swing.JComboBox<String> availMonthCBox;
    private javax.swing.JFormattedTextField availYearTxt;
    private javax.swing.JComboBox<String> expireMonthCBox;
    private javax.swing.JFormattedTextField expireYearTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField menufYearTxt;
    private javax.swing.JTextField menufactureTxt;
    private javax.swing.JTextField modelNumTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JFormattedTextField seatCapacityTxt;
    private javax.swing.JTextField serialNumTxt;
    // End of variables declaration//GEN-END:variables

}
