/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.MasterTravelSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class CreateNewAirlinerJPanel extends javax.swing.JPanel {

    private TravelAgency travelAgency;
    /**
     * Creates new form CreateNewAirliners
     */
    JPanel userProcessContainer;

    public CreateNewAirlinerJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airlinerNameTxt = new javax.swing.JTextField();
        saveNewAirlinerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        addFlightBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        iataCodeTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Create New Airliners");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        jLabel2.setText("Airliner Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        add(airlinerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 83, 126, -1));

        saveNewAirlinerBtn.setText("Create Airliners");
        saveNewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewAirlinerBtnActionPerformed(evt);
            }
        });
        add(saveNewAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 180, -1, -1));

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 253, -1, -1));

        addFlightBtn.setText("Add Flights");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });
        add(addFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 253, -1, -1));

        jLabel3.setText("IATA Code:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        add(iataCodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        // refreshTable
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinersWorkAreaJPanel manageAirlinersWorkAreaJPanel = (ManageAirlinersWorkAreaJPanel) component;
        manageAirlinersWorkAreaJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_backBtnActionPerformed

    private void saveNewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        if (airlinerNameTxt.getText().equals("") || iataCodeTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No blank field is allowed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner airliner = travelAgency.getAirlinerDir().addAirliner();
        airliner.setAirlinerName(airlinerNameTxt.getText());
        airliner.setIataCode(iataCodeTxt.getText());
        
        JOptionPane.showMessageDialog(null, "Airliner Successfully created.");
    }//GEN-LAST:event_saveNewAirlinerBtnActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
        CreateNewFlightJPanel panel = new CreateNewFlightJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("AccountMngWorkAreaJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextField airlinerNameTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField iataCodeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveNewAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
