/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageAirlinersWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    public ManageAirlinersWorkAreaJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) airlinerTbl.getModel();
        dtm.setRowCount(0);
        for (Airliner airliner: travelAgency.getAirlinerDir().getAirlinerList()) {
            Object[] row = new Object[2];
            row[0] = airliner;
            try { row[1] = airliner.getFSCatalog().getFlightSchedule().size(); }
            catch (Exception e) {
                row[1] = "0"; }
            dtm.addRow(row);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAirlinerBtn = new javax.swing.JButton();
        searchAirlinerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerSearchTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        airlinerTbl = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAirlinerBtn.setText("Create New Airliners");
        createAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerBtnActionPerformed(evt);
            }
        });
        add(createAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 140, -1));

        searchAirlinerBtn.setText("Search Airliners");
        searchAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAirlinerBtnActionPerformed(evt);
            }
        });
        add(searchAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 135, -1));

        airlinerSearchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Other Fields"
            }
        ));
        jScrollPane1.setViewportView(airlinerSearchTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 419, 279, 97));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Search Airliners Results");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 384, -1, -1));

        airlinerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Flight Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(airlinerTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 111, -1, 97));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 267, 120, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 305, 120, -1));

        jButton3.setText("Select");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 218, -1, -1));

        jLabel2.setText("Airliners");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 267, 53, -1));

        jLabel3.setText("Other Fields");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 308, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Manage Airliners");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 21, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("All Airliners");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 75, -1, -1));

        jButton4.setText("Update");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jButton5.setText("Select and Manage Flights");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAirlinerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAirlinerBtnActionPerformed

    private void createAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel panel = new CreateNewAirlinerJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("CreateNewAirlinersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_createAirlinerBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ManageFlightWorkAreaJPanel panel = new ManageFlightWorkAreaJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageFlightWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinerSearchTbl;
    private javax.swing.JTable airlinerTbl;
    private javax.swing.JButton createAirlinerBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton searchAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
