/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ftl
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private Person person;
    public CreatePanel(Person person) {
        initComponents();
        this.person = person;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        PrimaryPanel = new javax.swing.JPanel();
        firstNameTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        dobLabel = new javax.swing.JLabel();
        dobMonthComboBox = new javax.swing.JComboBox<>();
        dobDayTextField = new javax.swing.JTextField();
        dobYearTextField = new javax.swing.JTextField();
        savePrimaryButton = new javax.swing.JButton();
        uploadBtn = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        LicensePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNumTextField = new javax.swing.JTextField();
        saveLienseBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lClassComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lHeightFootTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lHeightInchTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lWeightTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lExpDateTextField = new javax.swing.JTextField();
        CreditCardPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cExpMonthComboBox = new javax.swing.JComboBox<>();
        cExpYearTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cPayDueDateTextField = new javax.swing.JTextField();
        cAccNumTextField = new javax.swing.JTextField();
        cBalanceTextField = new javax.swing.JTextField();
        cCreditLimitTextField = new javax.swing.JTextField();
        saveCreditCardBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AddressPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        aLine2TextField = new javax.swing.JTextField();
        aCityTextField = new javax.swing.JTextField();
        aStateTextField = new javax.swing.JTextField();
        aZipCodeTextField = new javax.swing.JTextField();
        aCountryTextField = new javax.swing.JTextField();
        saveAddressBtn = new javax.swing.JButton();
        aLine1TextField = new javax.swing.JTextField();
        FinancialPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        fAccNumTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fCDateTextField = new javax.swing.JTextField();
        fARadioButton = new javax.swing.JRadioButton();
        fInRadioButton = new javax.swing.JRadioButton();
        fDebtTextField = new javax.swing.JTextField();
        fCreditTextField = new javax.swing.JTextField();
        saveFinancialBtn = new javax.swing.JButton();

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        genderLabel.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female"}));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        dobLabel.setText("Date of Birth");

        dobMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar",
            "Apr", "May","Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"}));

savePrimaryButton.setText("Save");
savePrimaryButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        savePrimaryButtonActionPerformed(evt);
    }
    });

    uploadBtn.setText("Upload Portiait");
    uploadBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            uploadBtnActionPerformed(evt);
        }
    });

    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourse/icon-people.jpg"))); // NOI18N

    jLabel2.setText("SSN");

    javax.swing.GroupLayout PrimaryPanelLayout = new javax.swing.GroupLayout(PrimaryPanel);
    PrimaryPanel.setLayout(PrimaryPanelLayout);
    PrimaryPanelLayout.setHorizontalGroup(
        PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrimaryPanelLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PrimaryPanelLayout.createSequentialGroup()
                    .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PrimaryPanelLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(firstNameLabel)
                            .addGap(10, 10, 10))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrimaryPanelLayout.createSequentialGroup()
                            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(genderLabel)
                                .addComponent(lastNameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PrimaryPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(dobLabel)))
            .addGap(86, 86, 86)
            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(93, 93, 93))
        .addGroup(PrimaryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(PrimaryPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(ssnTextField))
                .addGroup(PrimaryPanelLayout.createSequentialGroup()
                    .addComponent(dobMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dobDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dobYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrimaryPanelLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(uploadBtn)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrimaryPanelLayout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(savePrimaryButton)
                    .addGap(104, 104, 104))))
    );
    PrimaryPanelLayout.setVerticalGroup(
        PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PrimaryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(PrimaryPanelLayout.createSequentialGroup()
                    .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstNameLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameLabel)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderLabel)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dobLabel))
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dobMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dobDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dobYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(uploadBtn))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(savePrimaryButton)
                .addGroup(PrimaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(64, Short.MAX_VALUE))
    );

    jTabbedPane.addTab("Primary", PrimaryPanel);

    jLabel1.setText("Number");

    saveLienseBtn.setText("Save");
    saveLienseBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveLienseBtnActionPerformed(evt);
        }
    });

    jLabel3.setText("Class");

    lClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "M" }));

    jLabel4.setText("Expiration Date");

    jLabel5.setText("Height");

    jLabel6.setText("Weight");

    jLabel7.setText("ft");

    jLabel8.setText("in");

    jLabel9.setText("lb");

    javax.swing.GroupLayout LicensePanelLayout = new javax.swing.GroupLayout(LicensePanel);
    LicensePanel.setLayout(LicensePanelLayout);
    LicensePanelLayout.setHorizontalGroup(
        LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicensePanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saveLienseBtn)
            .addGap(56, 56, 56))
        .addGroup(LicensePanelLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LicensePanelLayout.createSequentialGroup()
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGap(51, 51, 51)
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(LicensePanelLayout.createSequentialGroup()
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4))
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LicensePanelLayout.createSequentialGroup()
                            .addComponent(lHeightFootTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lHeightInchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(LicensePanelLayout.createSequentialGroup()
                            .addComponent(lWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))
                        .addComponent(lExpDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(241, Short.MAX_VALUE))
    );
    LicensePanelLayout.setVerticalGroup(
        LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(LicensePanelLayout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(lClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(lExpDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(11, 11, 11)
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(lHeightFootTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)
                .addComponent(lHeightInchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LicensePanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addContainerGap(82, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicensePanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveLienseBtn)
                    .addGap(50, 50, 50))))
    );

    jTabbedPane.addTab("License", LicensePanel);

    jLabel10.setText("Account Number");

    jLabel11.setText("Expiration Date");

    cExpMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar",
        "Apr", "May","Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"}));

jLabel12.setText("Balance");

jLabel13.setText("Credit Limit");

jLabel14.setText("Payment Due Date");

saveCreditCardBtn.setText("Save");
saveCreditCardBtn.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    saveCreditCardBtnActionPerformed(evt);
    }
    });

    jLabel15.setText("$");

    jLabel16.setText("$");

    javax.swing.GroupLayout CreditCardPanelLayout = new javax.swing.GroupLayout(CreditCardPanel);
    CreditCardPanel.setLayout(CreditCardPanelLayout);
    CreditCardPanelLayout.setHorizontalGroup(
        CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CreditCardPanelLayout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditCardPanelLayout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addGap(18, 18, 18)
                    .addComponent(cAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CreditCardPanelLayout.createSequentialGroup()
                    .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGap(24, 24, 24)
                    .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CreditCardPanelLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cExpMonthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cExpYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CreditCardPanelLayout.createSequentialGroup()
                    .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CreditCardPanelLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cCreditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreditCardPanelLayout.createSequentialGroup()
                            .addComponent(cPayDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(saveCreditCardBtn)))))
            .addContainerGap(128, Short.MAX_VALUE))
    );
    CreditCardPanelLayout.setVerticalGroup(
        CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CreditCardPanelLayout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(cAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(cExpMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cExpYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(cBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel16))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(cCreditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15))
            .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditCardPanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cPayDueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(80, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreditCardPanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                    .addComponent(saveCreditCardBtn)
                    .addGap(50, 50, 50))))
    );

    jTabbedPane.addTab("Credit Card", CreditCardPanel);

    jLabel17.setText("Street LIne 1");

    jLabel18.setText("Street Line 2");

    jLabel19.setText("City");

    jLabel20.setText("State");

    jLabel21.setText("Zip Code");

    jLabel22.setText("Country");

    saveAddressBtn.setText("Save");
    saveAddressBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveAddressBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
    AddressPanel.setLayout(AddressPanelLayout);
    AddressPanelLayout.setHorizontalGroup(
        AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddressPanelLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddressPanelLayout.createSequentialGroup()
                    .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19))
                    .addGap(50, 385, Short.MAX_VALUE))
                .addGroup(AddressPanelLayout.createSequentialGroup()
                    .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddressPanelLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AddressPanelLayout.createSequentialGroup()
                                    .addComponent(aCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveAddressBtn))
                                .addGroup(AddressPanelLayout.createSequentialGroup()
                                    .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(aZipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(AddressPanelLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(aLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(48, 48, 48))))
    );
    AddressPanelLayout.setVerticalGroup(
        AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AddressPanelLayout.createSequentialGroup()
            .addGap(13, 13, 13)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(aLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(aLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel19)
                .addComponent(aCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(13, 13, 13)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel20)
                .addComponent(aStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel21)
                .addComponent(aZipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddressPanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(aCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressPanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveAddressBtn)
                    .addGap(44, 44, 44))))
    );

    jTabbedPane.addTab("Address", AddressPanel);

    jLabel23.setText("Account Number");

    jLabel24.setText("Creation Date");

    jLabel25.setText("Status");

    jLabel26.setText("Debt");

    jLabel27.setText("Credit");

    buttonGroup1.add(fARadioButton);
    fARadioButton.setText("Active");

    buttonGroup1.add(fInRadioButton);
    fInRadioButton.setText("Inactive");

    saveFinancialBtn.setText("Save");
    saveFinancialBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveFinancialBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout FinancialPanelLayout = new javax.swing.GroupLayout(FinancialPanel);
    FinancialPanel.setLayout(FinancialPanelLayout);
    FinancialPanelLayout.setHorizontalGroup(
        FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FinancialPanelLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FinancialPanelLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel25)
                    .addGap(18, 18, 18)
                    .addComponent(fARadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fInRadioButton))
                .addGroup(FinancialPanelLayout.createSequentialGroup()
                    .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24))
                    .addGap(18, 18, 18)
                    .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fCDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(FinancialPanelLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel27)
                        .addComponent(jLabel26))
                    .addGap(18, 18, 18)
                    .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fDebtTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(fCreditTextField))))
            .addContainerGap(165, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinancialPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saveFinancialBtn)
            .addGap(49, 49, 49))
    );
    FinancialPanelLayout.setVerticalGroup(
        FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(FinancialPanelLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23)
                .addComponent(fAccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fCDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(fARadioButton))
                .addComponent(fInRadioButton))
            .addGap(17, 17, 17)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel26)
                .addComponent(fDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(8, 8, 8)
            .addGroup(FinancialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel27)
                .addComponent(fCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(saveFinancialBtn)
            .addGap(40, 40, 40))
    );

    jTabbedPane.addTab("Financial", FinancialPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }   
    
    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // Open File Chooser
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        switch (result) {
        case JFileChooser.APPROVE_OPTION:
            //System.out.println("Approve (Open or Save) was clicked");
            File imgFile = chooser.getSelectedFile();
            String imgPath = imgFile.getAbsolutePath();
            //Read the image as bufferedimage
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(imgPath));
            } catch (IOException e) {
                e.printStackTrace();
            }
            //Resize the BufferedImage
            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
            Image.SCALE_SMOOTH);
            //Display person portrait in appropriate size
            imageLabel.setIcon(new javax.swing.ImageIcon(dimg)); 
            break;
        case JFileChooser.CANCEL_OPTION:
            //System.out.println("Cancel or the close-dialog icon was clicked");
            break;
        case JFileChooser.ERROR_OPTION:
            //System.out.println("Error");
            break;
    }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void savePrimaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePrimaryButtonActionPerformed
        // Binding the user input to the person object
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());
        person.setGender((String)genderComboBox.getSelectedItem());
        person.setDobMonth((String)genderComboBox.getSelectedItem());
        person.setDobDay(Integer.parseInt(dobDayTextField.getText()));
        person.setDobYear(Integer.parseInt(dobYearTextField.getText()));
        person.setSsn(Integer.parseInt(ssnTextField.getText()));
        
        // Prompt user that person was successfully created.
        JOptionPane.showMessageDialog(null,"Create Primary Profile Successfully");
    }//GEN-LAST:event_savePrimaryButtonActionPerformed

    private void saveLienseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLienseBtnActionPerformed
        // Binding the user input to the license data object
        person.license.setLicenseNum(lNumTextField.getText());
        person.license.setClassType((String)lClassComboBox.getSelectedItem());
        person.license.setExpirationDate(lExpDateTextField.getText());
        person.license.setWeight(Integer.parseInt(lWeightTextField.getText()));
        person.license.setHeightFoot(Integer.parseInt(lHeightFootTextField.getText()));
        person.license.setHeightInch(Integer.parseInt(lHeightInchTextField.getText()));
        // Prompt user that license data was successfully created.
        JOptionPane.showMessageDialog(null,"Create License Data Successfully");
    }//GEN-LAST:event_saveLienseBtnActionPerformed

    private void saveCreditCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCreditCardBtnActionPerformed
        // Binding the user input to the credit card object
        person.creditCard.setAccountNum(Integer.parseInt(cAccNumTextField.getText()));
        person.creditCard.setExpMonth((String)cExpMonthComboBox.getSelectedItem());
        person.creditCard.setExpYear(Integer.parseInt(cExpYearTextField.getText()));
        person.creditCard.setBalance(Integer.parseInt(cBalanceTextField.getText()));
        person.creditCard.setCreditLimit(Integer.parseInt(cCreditLimitTextField.getText()));
        person.creditCard.setPaymentDueDate(cPayDueDateTextField.getText());
        // Prompt user that credit card was successfully created.
        JOptionPane.showMessageDialog(null,"Create Credit Card Data Successfully");
    }//GEN-LAST:event_saveCreditCardBtnActionPerformed

    private void saveAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAddressBtnActionPerformed
        // Binding the user input to the address object
        person.address.setLine1(aLine1TextField.getText());
        person.address.setLine2(aLine2TextField.getText());
        person.address.setCity(aCityTextField.getText());
        person.address.setState(aStateTextField.getText());
        person.address.setZipCode(Integer.parseInt(aZipCodeTextField.getText()));
        person.address.setCountry(aCountryTextField.getText());
        // Prompt user that address was successfully created.
        JOptionPane.showMessageDialog(null,"Create Address Data Successfully");
    }//GEN-LAST:event_saveAddressBtnActionPerformed

    private void saveFinancialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFinancialBtnActionPerformed
        // Judge RadioButton
        boolean status;
        if(buttonGroup1.getSelection().equals(fARadioButton.getModel()))
            status = true;
        else
            status = false;

        // Binding the user input to the financial accounts object
        person.financialAcc.setAccountNum(Integer.parseInt(fAccNumTextField.getText()));
        person.financialAcc.setCreationDate(fCDateTextField.getText());
        person.financialAcc.setStatus(status);
        person.financialAcc.setDebt(Integer.parseInt(fDebtTextField.getText()));
        person.financialAcc.setCredit(Integer.parseInt(fCreditTextField.getText()));
        // Prompt user that financial accounts were successfully created.
        JOptionPane.showMessageDialog(null,"Create Financial Accounts Data Successfully");
    }//GEN-LAST:event_saveFinancialBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JPanel CreditCardPanel;
    private javax.swing.JPanel FinancialPanel;
    private javax.swing.JPanel LicensePanel;
    private javax.swing.JPanel PrimaryPanel;
    private javax.swing.JTextField aCityTextField;
    private javax.swing.JTextField aCountryTextField;
    private javax.swing.JTextField aLine1TextField;
    private javax.swing.JTextField aLine2TextField;
    private javax.swing.JTextField aStateTextField;
    private javax.swing.JTextField aZipCodeTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cAccNumTextField;
    private javax.swing.JTextField cBalanceTextField;
    private javax.swing.JTextField cCreditLimitTextField;
    private javax.swing.JComboBox<String> cExpMonthComboBox;
    private javax.swing.JTextField cExpYearTextField;
    private javax.swing.JTextField cPayDueDateTextField;
    private javax.swing.JTextField dobDayTextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JComboBox<String> dobMonthComboBox;
    private javax.swing.JTextField dobYearTextField;
    private javax.swing.JRadioButton fARadioButton;
    private javax.swing.JTextField fAccNumTextField;
    private javax.swing.JTextField fCDateTextField;
    private javax.swing.JTextField fCreditTextField;
    private javax.swing.JTextField fDebtTextField;
    private javax.swing.JRadioButton fInRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JComboBox<String> lClassComboBox;
    private javax.swing.JTextField lExpDateTextField;
    private javax.swing.JTextField lHeightFootTextField;
    private javax.swing.JTextField lHeightInchTextField;
    private javax.swing.JTextField lNumTextField;
    private javax.swing.JTextField lWeightTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton saveAddressBtn;
    private javax.swing.JButton saveCreditCardBtn;
    private javax.swing.JButton saveFinancialBtn;
    private javax.swing.JButton saveLienseBtn;
    private javax.swing.JButton savePrimaryButton;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
